[package]
name = "paq"
version = "0.1.0"
authors = ["Silvio Henrique Ferreira <shferreira@me.com>"]
edition = "2018"

[dependencies]
"miniqueue" = "0.1.2"
"js-resolve" = "0.1.3"

[profile.release]
panic = 'abort'
