[package]
name = "paq"
version = "0.1.0"
authors = ["Silvio Henrique Ferreira <shferreira@me.com>"]
edition = "2018"

[dependencies]
json = "0.12"
memchr = "1.0.1"
unicode-xid = "0.1.0"

[profile.release]
panic = 'abort'
