name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: Install grcov
      run: cargo install grcov
    - name: Format
      run: cargo fmt -- --check
    - name: Lint
      run: cargo clippy -- -D warnings -D clippy::all -D clippy::nursery
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose --all-features --no-fail-fast
      env:
        'CARGO_INCREMENTAL': '0'
        'RUSTFLAGS': '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zno-landing-pads'
    - name: Bench
      run: cargo bench
    - name: Generate coverage
      run: grcov . -t lcov > coverage.info
    - name: Coveralls upload
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage.info
